#!/bin/bash
set -e

echo "Launching post-installation script ..."

# create virtual environment if it does not exist yet
if [ ! -d "/usr/share/ocsinventory-backend/venv" ]; then
    echo "Creating virtual environment ..."
    python3 -m venv /usr/share/ocsinventory-backend/venv
fi

echo "Activating virtual environment ..."
# Activate virtual environment
source /usr/share/ocsinventory-backend/venv/bin/activate

echo "Installing requirements ..."
# Install requirements
pip3 install -r /usr/share/ocsinventory-backend/requirements.txt

# Deactivate virtual environment
deactivate

# if there is a backup directory, restore the configuration, else cp the configuration
if [ -d "/usr/share/ocsinventory-backend-backup" ]; then
    UPDATE=1
else
    UPDATE=0
fi

if [ $UPDATE -eq 1 ]; then
    echo "Restoring Nginx and UWSGI configuration ..."
    # restore UWSGI configuration
    if [ -f /usr/share/ocsinventory-backend-backup/ocsinventory-backend.ini ]; then
        cp /usr/share/ocsinventory-backend-backup/ocsinventory-backend.ini /etc/uwsgi/apps-available/ocsinventory-backend.ini
    fi

    # restore NGINX configuration
    if [ -f /usr/share/ocsinventory-backend-backup/ocsinventory-backend ]; then
        cp /usr/share/ocsinventory-backend-backup/ocsinventory-backend /etc/nginx/sites-available/ocsinventory-backend
    fi
fi

# enable NGINX configuration
if [ ! -L /etc/nginx/sites-enabled/ocsinventory-backend ]; then
    ln -s /etc/nginx/sites-available/ocsinventory-backend /etc/nginx/sites-enabled/
fi

# enable UWSGI configuration
if [ ! -L /etc/uwsgi/apps-enabled/ocsinventory-backend.ini ]; then
    ln -s /etc/uwsgi/apps-available/ocsinventory-backend.ini /etc/uwsgi/apps-enabled/
fi

# run migrate 
echo "Running database migrations ..."
source /usr/share/ocsinventory-backend/venv/bin/activate
python3 /usr/share/ocsinventory-backend/manage.py migrate
deactivate

echo "Setting ownership and permissions ..."
# change ownership and permissions on logs directory
chown -R www-data:www-data /usr/share/ocsinventory-backend/
chmod -R 755 /usr/share/ocsinventory-backend/logs

echo "Restarting services ..."
# restart services
systemctl restart uwsgi
systemctl restart nginx

if [ $UPDATE -eq 1 ]; then
    echo "Removing backup directory ..."
    rm -rf /usr/share/ocsinventory-backend-backup
fi

echo "Post-installation script completed successfully, update or installation completed.
Please edit nginx configuration server_name to match your domain name and restart nginx service.
Additonnal database configuration may be required in /usr/share/ocsinventory-backend/ocsinventory_backend/settings.py."
