#!/bin/sh
set -e

# is this an update or a new install ?
if [ -d /usr/share/ocsinventory-backend ]; then
    echo "============================================"
    echo "=                                          ="
    echo "=      Updating OCS Inventory Backend      ="
    echo "=                                          ="
    echo "============================================"
    echo "Backing up existing OCS Inventory Backend installation ..."
    # create a backup dir
    mkdir -p /usr/share/ocsinventory-backend-backup

    # backup nginx and uwsgi conf
    if [ -f /etc/nginx/sites-available/ocsinventory-backend ]; then
        cp /etc/nginx/sites-available/ocsinventory-backend /usr/share/ocsinventory-backend-backup/ocsinventory-backend
    fi
    if [ -f /etc/uwsgi/apps-available/ocsinventory-backend.ini ]; then
        cp /etc/uwsgi/apps-available/ocsinventory-backend.ini /usr/share/ocsinventory-backend-backup/ocsinventory-backend.ini
    fi
    # backup settings.py
    if [ -f /usr/share/ocsinventory-backend/ocsinventory_backend/settings.py ]; then
        cp /usr/share/ocsinventory-backend/ocsinventory_backend/settings.py /usr/share/ocsinventory-backend-backup/settings.py
    fi
    # backup .env file
    if [ -f /usr/share/ocsinventory-backend/.env ]; then
        cp /usr/share/ocsinventory-backend/.env /usr/share/ocsinventory-backend-backup/.env
    fi
else
    echo "=============================================="
    echo "=                                            ="
    echo "=      Installing OCS Inventory Backend      ="
    echo "=                                            ="
    echo "=============================================="
fi