#!/bin/sh
set -e

# dh_installsystemd --no-start does not generate the stop on removal
if [ "$1" = remove ] && [ -d /run/systemd/system ]; then
    systemctl stop ocsinventory-backend-automation.timer ocsinventory-backend-automation.service >/dev/null 2>&1 || true
fi

#DEBHELPER#

exit 0
