server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    server_tokens off;

    root /usr/share/ocsinventory-frontend;
    index index.html;

    access_log /var/log/ocsinventory-frontend/access.log;
    error_log  /var/log/ocsinventory-frontend/error.log;

    location = /favicon.ico { access_log off; log_not_found off; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}