[uwsgi]
# Django-related settings
project = ocsinventory_backend
base = /opt/ocsinventory-backend
chdir = /opt/ocsinventory-backend
plugins = python3

# the virtualenv (if applicable)
home = /opt/ocsinventory-backend/venv

# Django's wsgi file
module = ocsinventory_backend.wsgi:application

# process-related settings
master = true
processes = 5

# the socket (use the full path to avoid any problems)
socket = /opt/ocsinventory-backend/application.sock
chmod-socket = 666
vacuum = true

# Log settings
logto = /var/log/uwsgi/ocsinventory-backend.log