[uwsgi]
# Django-related settings
project = ocsinventory_backend
base = /usr/share/ocsinventory-backend
chdir = /usr/share/ocsinventory-backend
plugins = python3

# the virtualenv (if applicable)
home = /usr/lib/ocsinventory-backend/venv

# Django's wsgi file
module = ocsinventory_backend.wsgi:application

# process-related settings
master = true
processes = 5

# the socket (use the full path to avoid any problems)
socket = /var/run/uwsgi/app/ocsinventory-backend/socket
chmod-socket = 644
vacuum = true

# Log settings
logto = /var/log/uwsgi/ocsinventory-backend.log