server {
    listen 8081;
    listen [::]:8081;
    server_name _;

    server_tokens off;

    access_log /var/log/ocsinventory-backend/access.log;
    error_log  /var/log/ocsinventory-backend/error.log;

    client_max_body_size 64m;

    location = /favicon.ico { access_log off; log_not_found off; }

    location /static/ {
        root /usr/share/ocsinventory-backend/;
    }

    location / {
        include         uwsgi_params;
        uwsgi_pass      unix:/var/run/ocsinventory-backend/ocsinventory-backend.sock;
        uwsgi_param     UWSGI_SCHEME $scheme;
        uwsgi_param     SERVER_SOFTWARE nginx/$nginx_version;
        uwsgi_read_timeout 300;
    }
}