#!/bin/sh
set -e

echo "Clean OCS Inventory Frontend files..."
rm -rf /usr/share/ocsinventory-frontend
rm -rf /var/log/ocsinventory-frontend
rm -rf /var/lib/ocsinventory-frontend-update
echo "OCS Inventory Frontend successfully uninstalled."
