version: '3'
services:
  ocsinventory-frontend :
    image : ocsinventory/ocsinventory-frontend:0.1.0
    container_name : ocsinventory-frontend
    restart: always
    ports :
      - "8080:80"
    volumes :
      - ocsinventory-frontend-config:/usr/share/ocsinventory-frontend/config

volumes:
  ocsinventory-frontend-config: